# -------- CUSTOMIZE ABILITY --------

# Automatically repair all damaged tools in player inventory
# true: auto-repair false: default repair
auto-repair: false

# Configure the auto repair (suggested by SuperBeacon)
auto-repair-config:
  # The consumed experience for each repair by the auto-repair (default: 20)
  expConsumed: 20

# Prevent mending item destroy when you don't have enough experience
# true: prevent destroy false: default destroy
prevent-destroy: false

# Configure the cooldown (suggested by Kad_L)
cooldown:
  # The cooldown between each use of the ability per player. This isn't applied to auto-repair
  # The cooldown in seconds (0 = disabled) (default: 0)
  time: 0

  # Number of uses before the cooldown acts (default: 3)
  uses: 3

  # True if the cooldown message should be shown
  # default: true
  message: true

  # True if the cooldown should do a sound
  # default: true
  sound: true

  # The cooldown text, $s is the actual remaining seconds
  text: "&4Please wait $s seconds before using this ability!"

# The removed experience when the mending ability is used
# You'd better use ratio instead
# You can use %exp% to manipulate player experience with operations, like "%exp% - 20"
# default: "20"
expValue: "20"

# A multiplier for the gained durability
# default: 2.0
ratio: 2.0

# -------- AUTO-REPAIR --------

# auto-repair must be set to true to use these functionalities!

# The delay (in ticks) between each tool's repair
# 20 ticks = 1 second
# default: 40
delay: 40

# True if auto-repair should repair the full inventory for every [delay] ticks or false if it should only repair one tool for every [delay] ticks
# default: true
repairFullInventory: true

# -------- SOUNDS --------

# Should play a sound if the power of mending is used.
# true: played / false: not played
playSound: true

# The volume of the sound, 1 is default
soundVolume: 1

# The speed of the sound, 1 is default, smaller than 1 is slower
soundPitch: 1

# -------- PARTICLES --------
# Enable or disable the particles
playEffect: true

# The particles range from the player (suggested by Kad_L)
range: 3

# The color used for particles (RGB, each value need to be between 0 and 255)
# default (in the order of color): 144, 238, 144
color:
  red: 144
  green: 238
  blue: 144

# The offset of particles, from the player feet location. Can be a negative value
offset:
  x: 0.0
  y: 0.0
  z: 0.0

## -------- BLACKLISTS --------

# Players who are not allowed to use the mending ability
blacklisted-players:
  # Example:
  # - "radstevee"

# Items that are not allowed to be repaired
# Also support Oraxen items (with their name, not their display name)
blacklisted-items:
  # Example:
  # - "DIAMOND_SWORD"

## -------- CONFIGURATION --------
# Override the default plugin choice for data storage.
# If you want to use the file-based storage instead of persistent data container in 1.14+, set this to true.
# default: false
file-based: false

## -------- MISCELLANEOUS --------
# Disable or not statistics (help me to make my plugin better!)
bstat: true

# Please, do not touch!
version: 13